name: nodejsscan

on:
  pull_request:
  push:
    branches: [master]

jobs:
  nodejsscan:
    runs-on: ubuntu-latest
    name: nodejsscan check
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'