name: static-code-analysis

on: push
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CICD }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.2
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          dry: true
          prettier_version: 2.2.1
          prettier_options: --write .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: ${{ github.ref == 'refs/heads/main' && failure() }}
